dataset_params:
  root_dir: ../data/taichi
  frame_shape: [256, 256, 3]
  id_sampling: True
  pairs_list: #data/taichi256.csv
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
model_params:
  common_params:
    num_channels: 3
  mask_generator_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    th: 60
train_params:
  num_epochs: 100
  num_repeats: 150
  epoch_milestones: [60, 90]
  lr_generator: 2.0e-4
  lr_mask_generator: 2.0e-4
  batch_size: 20
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 1
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]

reconstruction_params:
  num_videos: 1000
  format: '.mp4'

animate_params:
  num_pairs: 50
  format: '.mp4'

visualizer_params:
  draw_border: True
  colormap: 'gist_rainbow'
